### ISSUE TITLE
Unclaimed Room With Spawn Error

### ISSUE THREAD

**Issue by torin555** [ScreepsOCS/screeps.behaviour-action-pattern#269]
If you unclaim a room or I would assume if the room degrades to 0 controller level and you have a spawn in it the console will get spammed with this unless you destroy the spawn:
`[10:44:09 PM]TypeError: Cannot read property 'minAbsEnergyAvailable' of undefined
    at Setup.isValidSetup (creep.Setup:68:56)
    at probe (spawn:21:30)
    at baseFindIndex (/opt/engine/node_modules/lodash/index.js:326:11)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3241:23)
    at Spawn.loop (spawn:23:15)
    at loop (spawn:41:27)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)`
I think this may also happen if the controller degrades and causes extentions to turn red.

**Comment by dkluempers** [comment]
I will take a crack at claiming a room then unclaiming it.

**Comment by dkluempers** [comment]
Rats - I have to wait for my GCL to go up.
