### ISSUE TITLE
Error lastest dev

### ISSUE THREAD

**Issue by Krazyfuq** [ScreepsOCS/screeps.behaviour-action-pattern#358]
only when updating the task.guard.js

[11:14:54 AM]ReferenceError: name is not defined
    at Creep.died.on.creep (task.guard:7:60)
    at handlers.slice.forEach.h (global:25:57)
    at Array.forEach (native)
    at LiteEvent.trigger (global:25:44)
    at register (population:162:28)
    at baseForOwn (E:\SteamLibrary\steamapps\common\Screeps\server\node_modules\lodash\index.js:2046:14)
    at Function.<anonymous> (E:\SteamLibrary\steamapps\common\Screeps\server\node_modules\lodash\index.js:3346:13)

**Comment by Krazyfuq** [comment]
perfect, thanks
