### ISSUE TITLE
Privateer Home Destroyed - Can't Withdraw

### ISSUE THREAD

**Issue by dkluempers** [ScreepsOCS/screeps.behaviour-action-pattern#370]
When I was attacked recently I got the following message:

[6:54:55 AM]TypeError: Cannot read property 'pos' of undefined
   at Object.run (creep.behaviour.privateer:24:30)
   at Creep.run (creep:109:43)
   at run (creep:58:38)
   at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
   at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)
   at Function.Creep.loop (creep:59:15)
   at Object.module.exports.loop (main:120:11)

Everything froze up.  I found a privateer that was stuck and then had him suicide and the error went away and things started working.  I think when the privateer trying to go home because it sees and enemy creep it can't find home and this causes the error.  I am trying to understand the code now.

**Comment by cyberblast** [comment]
I just removed those "flee" lines, as there is another flee evaluation and execution in creep.js, which overrides those "drive" orders anyway.
