### ISSUE TITLE
New dev error

### ISSUE THREAD

**Issue by Krazyfuq** [ScreepsOCS/screeps.behaviour-action-pattern#506]
From newest dev i get this error

[1:49:31 PM]Error loading module "./creep.action.uncharging"!
Error: Circular reference to module 'creep.action.uncharging'
[1:49:31 PM]Error loading module "./creep.action.uncharging"!
Error: Circular reference to module 'creep.action.uncharging'
[1:49:31 PM]TypeError: Cannot read property 'register' of null
    at Function.Creep.register (creep:113:41)
    at Object.module.exports.loop (main:133:11)
    at __mainLoop:1:52
    at ContextifyScript.Script.runInContext (vm.js:35:29)

Commenting out line main:133 has stopped the error, may break something else I dont know?

**Comment by cyberblast** [comment]
No, unless you implemented something it isn't registering anything right now... so you may comment out.

**Comment by cyberblast** [comment]
hard to debug, I'm not getting this one. 

if you are moving the last line (module.exports = ...) to the second line, like this: 
```
var action = new Creep.Action('uncharging'); // get from container
module.exports = action;
action.renewTarget = false;
[...]
```
does the error persist?

**Comment by Krazyfuq** [comment]
I removed the comments to make sure it was still happening, it was

I then as you suggest moved last line to 2nd line and error stopped.. thanks

**Comment by cyberblast** [comment]
oh, cool :) 
hmm we should then do that for all actions I guess...

**Comment by Krazyfuq** [comment]
Now it is throwing up this error

[4:18:58 PM]SyntaxError: Unexpected token .
    at Action.validateActionTarget (creep.Action:74:18)
    at validateAssignment (population:222:43)
    at baseForOwn (E:\SteamLibrary\steamapps\common\Screeps\server\node_modules\lodash\index.js:2046:14)
    at Function.<anonymous> (E:\SteamLibrary\steamapps\common\Screeps\server\node_modules\lodash\index.js:3346:13)
    at Object.loop (population:233:11)
    at Object.module.exports.loop (main:138:16)
    at __mainLoop:1:52

which only corrects when I put module.exports = action; back as the last line

**Comment by cyberblast** [comment]
We rearranged a lot regarding module loading. 
Is this issue still current?

**Comment by karlthepagan** [comment]
Is this still an issue @Krazyfuq ?
