### ISSUE TITLE
corrupt creep / cannot read 'flee' of undefined

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#572]
Seen this error a few times (usually after changing or modifying files), however had it a couple times randomly too, appears other people have had the same error. 

    [13:47:28] Corrupt creep without population entry!! : remoteHauler-Flag7-2
    [13:47:28] TypeError: Cannot read property 'flee' of undefined
    at get (creep:296:30)
    at Creep.run (creep:91:21)
    at run (creep:350:30)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)
    at Function.mod.execute (creep:351:7)
    at Object.module.exports.loop (main:256:11)

I checked the creep and it was alive and functioning properly. 

(not updated my code for 24 hours so could be fixed with recent/upcoming PR's, just posting for reference)

**Comment by Dasku** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/570/commits/59fb008d09f35ba639cc52d6d8e382d20628d2c6 

should fix this

**Comment by cyberblast** [comment]
yes. I was also thinking about if this requires a special handling, but as everything seems to be "normal" afterwards there must be creep data present. 
Also, there is a special handlling already in Population. 

So this should be an ignorable case as creep data gets set immediately afterwards. I also think this shouldn't happen anymore since the big main refactoring (distinct phases and population.execute gets called before creep.execute). 

a trace call may get set if desired...
