### ISSUE TITLE
worker errors

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#600]
Thought we fixed this a while ago, however this morning found a worker outside the main room (was working on a wall at the edge). Console was spamming nextAction of worker is undefined,

**Comment by Dasku** [comment]
Also getting this error today (I'm 99% sure its from a remote worker as it wasnt getting the error before building roads in a new mine room.)

[10:10:11] Script execution has been terminated due to a fatal error: TypeError: Converting circular structure to JSON

**Comment by Dasku** [comment]
Also somehow, the remote worker has picked up recycling action when there is still construction sites available, 

![image](https://cloud.githubusercontent.com/assets/22677773/22204100/1cdef7e4-e168-11e6-920e-cffedfb65e43.png)

**Comment by Dasku** [comment]
Still getting this on a fairly regular basis. No remote workers alive right now so I'm at a loss as to where this error is coming from.

ReferenceError: assigned is not defined
    at Object.mod.nextAction (creep.behaviour.worker:20:122)
    at Object.mod.run (creep.behaviour.worker:8:14)
    at Creep.run (creep:45:39)
    at run (creep:375:30)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)
    at Function.mod.execute (creep:376:7)
