### ISSUE TITLE
task.robbing tries to set an undefined in dev.

### ISSUE THREAD

**Issue by Modzer0** [ScreepsOCS/screeps.behaviour-action-pattern#743]
I would submit the hotfix, but I don't have access to do pull requests.
Added
                if(!creep.flag){
                    creep.flag = {}
                }
Above
                creep.flag.cloaking = 50;

[1:13:12 AM]TypeError: Cannot set property 'cloaking' of undefined
    at Object.mod.nextAction.creep [as nextAction] (task.robbing:209:37)
    at Object.mod.run (creep.behaviour.privateer:9:39)
    at Creep.run (creep:47:39)
    at run (creep:454:30)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)
    at Function.mod.execute (creep:455:7)

**Comment by karlthepagan** [comment]
Please review #744 and comment for now
