### ISSUE TITLE
Bug in creep.action.reallocating at Action.action.findNeeding 'length' of undefined

### ISSUE THREAD

**Issue by Kelturio** [ScreepsOCS/screeps.behaviour-action-pattern#776]
After updating to the newest dev build i get this error:

TypeError: Cannot read property 'length' of undefined
    at Action.action.findNeeding (creep.action.reallocating:111:22)
    at Action.action.work (creep.action.reallocating:404:32)
    at Action.step (creep.Action:54:35)
    at Object.mod.run (creep.behaviour.hauler:13:22)
    at Creep.run (creep:47:39)
    at run (creep:447:30)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)

have to revert this changes because all stopped working with this bug
Need help please

**Comment by Spedwards** [comment]
The line in question is `if (data.labs.length > 0) {`. This should resolve itself after a couple ticks.

**Comment by Kelturio** [comment]
i dropped the newest files again on my older build and now i seems fixed mkay^^

**Comment by Dasku** [comment]
also getting this recently (seems to fix just after)

[22:51:24] TypeError: Cannot read property 'structure' of null
    at Action.action.work (creep.action.reallocating:405:24)
    at Action.step (creep.Action:54:35)
    at Object.mod.run (creep.behaviour.hauler:13:22)
    at Creep.run (creep:47:39)
    at run (creep:447:30)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)

**Comment by Dasku** [comment]
was this fixed by 
4753643e932a09dfd079fb5fb8c75632395ab683  @logxen logxen committed with karlthepagan 15 hours ago 

if so we can close this one

**Comment by logxen** [comment]
yep ... the first one up there was still a bug though ... got it now :P
