### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#793]
[22:51:40] Error in room.js (Room.prototype.loop) for "E73N59": 
TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.exports.roomNameToXY (/opt/engine/dist/utils.js:351:16)
    at Object.exports.calcRoomsDistance (/opt/engine/dist/utils.js:991:42)
    at Object. (/opt/engine/dist/game/market.js:33:34)
    at Object.calcTransactionCost (evalmachine.:1:72)
    at Room.terminalBroker (room:1433:43)
    at getEnvironment (room:1914:22)
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
    at Function. (/opt/engine/node_modules/lodash/index.js:3346:13)
TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.exports.roomNameToXY (/opt/engine/dist/utils.js:351:16)
    at Object.exports.calcRoomsDistance (/opt/engine/dist/utils.js:991:42)
    at Object. (/opt/engine/dist/game/market.js:33:34)
    at Object.calcTransactionCost (evalmachine.:1:72)
    at Room.terminalBroker (room:1433:43)
    at getEnvironment (room:1914:22)
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
    at Function. (/opt/engine/node_modules/lodash/index.js:3346:13)

only on the 500 update tick, spams for each room

**Comment by karlthepagan** [comment]
I saw this a lot when I migrated to traveler.

**Comment by karlthepagan** [comment]
Oops, this isn't traveler related.

**Comment by Kelturio** [comment]
Error in room.js (Room.prototype.loop) for "E18N73": 
TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.exports.roomNameToXY (/opt/engine/dist/utils.js:351:16)
    at Object.exports.calcRoomsDistance (/opt/engine/dist/utils.js:991:42)
    at Object. (/opt/engine/dist/game/market.js:33:34)
    at Object.calcTransactionCost (evalmachine.:1:72)
    at Room.terminalBroker (room:1411:43)
    at getEnvironment (room:1891:22)
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
    at Function. (/opt/engine/node_modules/lodash/index.js:3346:13)
TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.exports.roomNameToXY (/opt/engine/dist/utils.js:351:16)
    at Object.exports.calcRoomsDistance (/opt/engine/dist/utils.js:991:42)
    at Object. (/opt/engine/dist/game/market.js:33:34)
    at Object.calcTransactionCost (evalmachine.:1:72)
    at Room.terminalBroker (room:1411:43)
    at getEnvironment (room:1891:22)
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
    at Function. (/opt/engine/node_modules/lodash/index.js:3346:13)
