### ISSUE TITLE
creep.travelTo is not a function in dev

### ISSUE THREAD

**Issue by jisaf** [ScreepsOCS/screeps.behaviour-action-pattern#846]
in dev branch creep.avoiding.js calls creep.travelTo, but there is no travelTo in the dev creep.js.

**Comment by Kelturio** [comment]
TypeError: creep.travelTo is not a function
    at Action.action.work (creep.action.avoiding:67:19)
    at Action.action.run (creep.action.avoiding:78:20)
    at Object.mod.run (creep.behaviour.remoteMiner:5:31)
    at Creep.run (creep:50:39)
    at run (creep:449:30)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)

**Comment by Spedwards** [comment]
In the mean time, I'd recommend running `canary`.

**Comment by Spedwards** [comment]
Resolved.
