### ISSUE TITLE
Errors in room.js 

### ISSUE THREAD

**Issue by Perrytheplatypus43** [ScreepsOCS/screeps.behaviour-action-pattern#994]
Errors in room.js : 

`Error in room.js (Room.prototype.loop) for "E89N58": 
ReferenceError: AUTO_POWER_MINING is not defined
    at getEnvironment (room:2691:16)
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
    at Function. (/opt/engine/node_modules/lodash/index.js:3346:13)
    at Function.mod.analyze (room:2699:7)
    at Object.module.exports.loop (main:275:10)
    at __module (__mainLoop:1:52)
    at __mainLoop:2:3
    at ContextifyScript.Script.runInContext (vm.js:35:29)
ReferenceError: AUTO_POWER_MINING is not defined
    at getEnvironment (room:2691:16)
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
    at Function. (/opt/engine/node_modules/lodash/index.js:3346:13)
    at Function.mod.analyze (room:2699:7)
    at Object.module.exports.loop (main:275:10)
    at __module (__mainLoop:1:52)
    at __mainLoop:2:3
    at ContextifyScript.Script.runInContext (vm.js:35:29)`

**Comment by chobobobo** [comment]
What branch are you running to see this area dev or canary?  Also, it sounds like some of your files might be inconsistent, try running `delete Memory.modules` from the console to see if it resolves this error.

**Comment by Perrytheplatypus43** [comment]
I am using canary, I will delete Memory.modules and see if that helps.

**Comment by Perrytheplatypus43** [comment]
It made two new errors:

The first one:
`TypeError: Cannot read property 'parameter' of undefined
    at global.getPath (main:35:46)
    at global.load (main:98:16)
    at Object.module.exports.loop (main:257:22)
    at __mainLoop:1:52`

=============================================

the second one:
`TypeError: Cannot read property 'global' of undefined
    at global.getPath (main:35:46)
    at global.load (main:98:16)
    at global.install (main:125:27)
    at main:230:8
    at ContextifyScript.Script.runInContext (vm.js:35:29)`

**Comment by chobobobo** [comment]
Very strange, I'm not at the computer at the moment so can't look up exactly what that means.  Are you using the internal.package including both the internal and public repositories or is this on the public only repository?

**Comment by Perrytheplatypus43** [comment]
Wright now i'm using the public only not the private one.

**Comment by chobobobo** [comment]
Ok I will build public only when I get home and get back to you again.

**Comment by chobobobo** [comment]
Ok, I've run public only and things are running fine.  I think you must have some files that are either the wrong version or missing in your deployment.  Try pushing all of your files again.

**Comment by Perrytheplatypus43** [comment]
I will try to update my code to the newest version but i cant do it now so ill do it later and see if it works.

**Comment by Perrytheplatypus43** [comment]
I updated my code to the newest version of canary and I still have the `TypeError: Cannot read property 'global' of undefined`

**Comment by chobobobo** [comment]
@Perrytheplatypus43 did we get this resolved in the end?
